### ISSUE TITLE
Missing pudge.txt file

### ISSUE THREAD

**Issue by headgame** [Shieroz/2D-MOBA#1]
Hi,bro.  Error Exisit : Could not find a part of the path "C:/Users/nghe1/Desktop/Pudge.txt".

Would you mind to upload Pudge.txt file?

**Comment by headgame** [comment]
Also miss config.yaml and model.nn file

**Comment by Shieroz** [comment]
Hey, thanks for the interested in my project. I have updated the Pudge.txt file into Assets/HeroFiles. As for the config.yaml and model.nn files, I have lost them so sorry about that. But those are files related to the ML-Agents so you can read up on Unity's documentation for them.

**Comment by headgame** [comment]
Thanks, I'll try it : )
